name: ff_annotation_route_core
description: The core library of ff_annotation_route.
version: 1.0.0
homepage: https://github.com/fluttercandies/ff_annotation_route_core

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
 meta: ^1.2.4

# dev_dependencies:
#   pedantic: ^1.9.0
#   test: ^1.14.4
