name: ff_annotation_route_core
description: The core library of ff_annotation_route, support both null-safety and non-null-safety.
version: 2.0.2-non-null-safety
homepage: https://github.com/fluttercandies/ff_annotation_route_core

environment:
  sdk: '>=2.6.0 <2.12.0'

dependencies:
 meta: ^1.2.4
