name: ff_annotation_route_core
description: The core library of ff_annotation_route.
version: 1.1.1-nullsafety
homepage: https://github.com/fluttercandies/ff_annotation_route_core

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

